package com.hongster.dis.common.model.system;

import java.io.Serializable;
import java.util.Date;

public class SysHospital implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.hospital_id
     *
     * @mbg.generated
     */
    private String hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.hospital_no
     *
     * @mbg.generated
     */
    private String hospitalNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.superior
     *
     * @mbg.generated
     */
    private String superior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.is_price
     *
     * @mbg.generated
     */
    private String isPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.is_automatic
     *
     * @mbg.generated
     */
    private String isAutomatic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.is_log
     *
     * @mbg.generated
     */
    private String isLog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.days
     *
     * @mbg.generated
     */
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.opening_date
     *
     * @mbg.generated
     */
    private Date openingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.accounts_name
     *
     * @mbg.generated
     */
    private String accountsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.appid
     *
     * @mbg.generated
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.secret
     *
     * @mbg.generated
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.aeskey
     *
     * @mbg.generated
     */
    private String aeskey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.create_by_
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.create_time_
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.update_by_
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.update_time_
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.data_status
     *
     * @mbg.generated
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_hospital.data_sync
     *
     * @mbg.generated
     */
    private String dataSync;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_hospital
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.hospital_id
     *
     * @return the value of sys_hospital.hospital_id
     *
     * @mbg.generated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.hospital_id
     *
     * @param hospitalId the value for sys_hospital.hospital_id
     *
     * @mbg.generated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.hospital_no
     *
     * @return the value of sys_hospital.hospital_no
     *
     * @mbg.generated
     */
    public String getHospitalNo() {
        return hospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.hospital_no
     *
     * @param hospitalNo the value for sys_hospital.hospital_no
     *
     * @mbg.generated
     */
    public void setHospitalNo(String hospitalNo) {
        this.hospitalNo = hospitalNo == null ? null : hospitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.hospital_name
     *
     * @return the value of sys_hospital.hospital_name
     *
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.hospital_name
     *
     * @param hospitalName the value for sys_hospital.hospital_name
     *
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.superior
     *
     * @return the value of sys_hospital.superior
     *
     * @mbg.generated
     */
    public String getSuperior() {
        return superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.superior
     *
     * @param superior the value for sys_hospital.superior
     *
     * @mbg.generated
     */
    public void setSuperior(String superior) {
        this.superior = superior == null ? null : superior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.tel
     *
     * @return the value of sys_hospital.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.tel
     *
     * @param tel the value for sys_hospital.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.address
     *
     * @return the value of sys_hospital.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.address
     *
     * @param address the value for sys_hospital.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.is_price
     *
     * @return the value of sys_hospital.is_price
     *
     * @mbg.generated
     */
    public String getIsPrice() {
        return isPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.is_price
     *
     * @param isPrice the value for sys_hospital.is_price
     *
     * @mbg.generated
     */
    public void setIsPrice(String isPrice) {
        this.isPrice = isPrice == null ? null : isPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.is_automatic
     *
     * @return the value of sys_hospital.is_automatic
     *
     * @mbg.generated
     */
    public String getIsAutomatic() {
        return isAutomatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.is_automatic
     *
     * @param isAutomatic the value for sys_hospital.is_automatic
     *
     * @mbg.generated
     */
    public void setIsAutomatic(String isAutomatic) {
        this.isAutomatic = isAutomatic == null ? null : isAutomatic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.is_log
     *
     * @return the value of sys_hospital.is_log
     *
     * @mbg.generated
     */
    public String getIsLog() {
        return isLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.is_log
     *
     * @param isLog the value for sys_hospital.is_log
     *
     * @mbg.generated
     */
    public void setIsLog(String isLog) {
        this.isLog = isLog == null ? null : isLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.days
     *
     * @return the value of sys_hospital.days
     *
     * @mbg.generated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.days
     *
     * @param days the value for sys_hospital.days
     *
     * @mbg.generated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.opening_date
     *
     * @return the value of sys_hospital.opening_date
     *
     * @mbg.generated
     */
    public Date getOpeningDate() {
        return openingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.opening_date
     *
     * @param openingDate the value for sys_hospital.opening_date
     *
     * @mbg.generated
     */
    public void setOpeningDate(Date openingDate) {
        this.openingDate = openingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.accounts_name
     *
     * @return the value of sys_hospital.accounts_name
     *
     * @mbg.generated
     */
    public String getAccountsName() {
        return accountsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.accounts_name
     *
     * @param accountsName the value for sys_hospital.accounts_name
     *
     * @mbg.generated
     */
    public void setAccountsName(String accountsName) {
        this.accountsName = accountsName == null ? null : accountsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.appid
     *
     * @return the value of sys_hospital.appid
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.appid
     *
     * @param appid the value for sys_hospital.appid
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.secret
     *
     * @return the value of sys_hospital.secret
     *
     * @mbg.generated
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.secret
     *
     * @param secret the value for sys_hospital.secret
     *
     * @mbg.generated
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.token
     *
     * @return the value of sys_hospital.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.token
     *
     * @param token the value for sys_hospital.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.aeskey
     *
     * @return the value of sys_hospital.aeskey
     *
     * @mbg.generated
     */
    public String getAeskey() {
        return aeskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.aeskey
     *
     * @param aeskey the value for sys_hospital.aeskey
     *
     * @mbg.generated
     */
    public void setAeskey(String aeskey) {
        this.aeskey = aeskey == null ? null : aeskey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.remark
     *
     * @return the value of sys_hospital.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.remark
     *
     * @param remark the value for sys_hospital.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.create_by_
     *
     * @return the value of sys_hospital.create_by_
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.create_by_
     *
     * @param createBy the value for sys_hospital.create_by_
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.create_time_
     *
     * @return the value of sys_hospital.create_time_
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.create_time_
     *
     * @param createTime the value for sys_hospital.create_time_
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.update_by_
     *
     * @return the value of sys_hospital.update_by_
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.update_by_
     *
     * @param updateBy the value for sys_hospital.update_by_
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.update_time_
     *
     * @return the value of sys_hospital.update_time_
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.update_time_
     *
     * @param updateTime the value for sys_hospital.update_time_
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.data_status
     *
     * @return the value of sys_hospital.data_status
     *
     * @mbg.generated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.data_status
     *
     * @param dataStatus the value for sys_hospital.data_status
     *
     * @mbg.generated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_hospital.data_sync
     *
     * @return the value of sys_hospital.data_sync
     *
     * @mbg.generated
     */
    public String getDataSync() {
        return dataSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_hospital.data_sync
     *
     * @param dataSync the value for sys_hospital.data_sync
     *
     * @mbg.generated
     */
    public void setDataSync(String dataSync) {
        this.dataSync = dataSync == null ? null : dataSync.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_hospital
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hospitalId=").append(hospitalId);
        sb.append(", hospitalNo=").append(hospitalNo);
        sb.append(", hospitalName=").append(hospitalName);
        sb.append(", superior=").append(superior);
        sb.append(", tel=").append(tel);
        sb.append(", address=").append(address);
        sb.append(", isPrice=").append(isPrice);
        sb.append(", isAutomatic=").append(isAutomatic);
        sb.append(", isLog=").append(isLog);
        sb.append(", days=").append(days);
        sb.append(", openingDate=").append(openingDate);
        sb.append(", accountsName=").append(accountsName);
        sb.append(", appid=").append(appid);
        sb.append(", secret=").append(secret);
        sb.append(", token=").append(token);
        sb.append(", aeskey=").append(aeskey);
        sb.append(", remark=").append(remark);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", dataStatus=").append(dataStatus);
        sb.append(", dataSync=").append(dataSync);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_hospital
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysHospital other = (SysHospital) that;
        return (this.getHospitalId() == null ? other.getHospitalId() == null : this.getHospitalId().equals(other.getHospitalId()))
            && (this.getHospitalNo() == null ? other.getHospitalNo() == null : this.getHospitalNo().equals(other.getHospitalNo()))
            && (this.getHospitalName() == null ? other.getHospitalName() == null : this.getHospitalName().equals(other.getHospitalName()))
            && (this.getSuperior() == null ? other.getSuperior() == null : this.getSuperior().equals(other.getSuperior()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getIsPrice() == null ? other.getIsPrice() == null : this.getIsPrice().equals(other.getIsPrice()))
            && (this.getIsAutomatic() == null ? other.getIsAutomatic() == null : this.getIsAutomatic().equals(other.getIsAutomatic()))
            && (this.getIsLog() == null ? other.getIsLog() == null : this.getIsLog().equals(other.getIsLog()))
            && (this.getDays() == null ? other.getDays() == null : this.getDays().equals(other.getDays()))
            && (this.getOpeningDate() == null ? other.getOpeningDate() == null : this.getOpeningDate().equals(other.getOpeningDate()))
            && (this.getAccountsName() == null ? other.getAccountsName() == null : this.getAccountsName().equals(other.getAccountsName()))
            && (this.getAppid() == null ? other.getAppid() == null : this.getAppid().equals(other.getAppid()))
            && (this.getSecret() == null ? other.getSecret() == null : this.getSecret().equals(other.getSecret()))
            && (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
            && (this.getAeskey() == null ? other.getAeskey() == null : this.getAeskey().equals(other.getAeskey()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDataStatus() == null ? other.getDataStatus() == null : this.getDataStatus().equals(other.getDataStatus()))
            && (this.getDataSync() == null ? other.getDataSync() == null : this.getDataSync().equals(other.getDataSync()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_hospital
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHospitalId() == null) ? 0 : getHospitalId().hashCode());
        result = prime * result + ((getHospitalNo() == null) ? 0 : getHospitalNo().hashCode());
        result = prime * result + ((getHospitalName() == null) ? 0 : getHospitalName().hashCode());
        result = prime * result + ((getSuperior() == null) ? 0 : getSuperior().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getIsPrice() == null) ? 0 : getIsPrice().hashCode());
        result = prime * result + ((getIsAutomatic() == null) ? 0 : getIsAutomatic().hashCode());
        result = prime * result + ((getIsLog() == null) ? 0 : getIsLog().hashCode());
        result = prime * result + ((getDays() == null) ? 0 : getDays().hashCode());
        result = prime * result + ((getOpeningDate() == null) ? 0 : getOpeningDate().hashCode());
        result = prime * result + ((getAccountsName() == null) ? 0 : getAccountsName().hashCode());
        result = prime * result + ((getAppid() == null) ? 0 : getAppid().hashCode());
        result = prime * result + ((getSecret() == null) ? 0 : getSecret().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result + ((getAeskey() == null) ? 0 : getAeskey().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDataStatus() == null) ? 0 : getDataStatus().hashCode());
        result = prime * result + ((getDataSync() == null) ? 0 : getDataSync().hashCode());
        return result;
    }
}