package com.origtek.oas.dialysis.dao.patient;

import com.origtek.oas.common.model.patient.PatPatientHistory;
import com.origtek.oas.common.model.patient.PatPatientHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PatPatientHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    long countByExample(PatPatientHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int deleteByExample(PatPatientHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String patientHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int insert(PatPatientHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int insertSelective(PatPatientHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    List<PatPatientHistory> selectByExampleWithBLOBsWithRowbounds(PatPatientHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    List<PatPatientHistory> selectByExampleWithBLOBs(PatPatientHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    List<PatPatientHistory> selectByExampleWithRowbounds(PatPatientHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    List<PatPatientHistory> selectByExample(PatPatientHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    PatPatientHistory selectByPrimaryKey(String patientHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PatPatientHistory record, @Param("example") PatPatientHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PatPatientHistory record, @Param("example") PatPatientHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PatPatientHistory record, @Param("example") PatPatientHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PatPatientHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PatPatientHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PatPatientHistory record);
}