package com.hongster.dis.system.dialysis;

import com.hongster.dis.common.model.dialysis.DiaSummary;
import com.hongster.dis.common.model.dialysis.DiaSummaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DiaSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    long countByExample(DiaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    int deleteByExample(DiaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String summaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    int insert(DiaSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    int insertSelective(DiaSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    List<DiaSummary> selectByExampleWithRowbounds(DiaSummaryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    List<DiaSummary> selectByExample(DiaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    DiaSummary selectByPrimaryKey(String summaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DiaSummary record, @Param("example") DiaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DiaSummary record, @Param("example") DiaSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DiaSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DiaSummary record);
}