package com.hongster.dis.common.model.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysDictDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public SysDictDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNull() {
            addCriterion("dict_id is null");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNotNull() {
            addCriterion("dict_id is not null");
            return (Criteria) this;
        }

        public Criteria andDictIdEqualTo(String value) {
            addCriterion("dict_id =", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotEqualTo(String value) {
            addCriterion("dict_id <>", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThan(String value) {
            addCriterion("dict_id >", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThanOrEqualTo(String value) {
            addCriterion("dict_id >=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThan(String value) {
            addCriterion("dict_id <", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThanOrEqualTo(String value) {
            addCriterion("dict_id <=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLike(String value) {
            addCriterion("dict_id like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotLike(String value) {
            addCriterion("dict_id not like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdIn(List<String> values) {
            addCriterion("dict_id in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotIn(List<String> values) {
            addCriterion("dict_id not in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdBetween(String value1, String value2) {
            addCriterion("dict_id between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotBetween(String value1, String value2) {
            addCriterion("dict_id not between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictDataNameIsNull() {
            addCriterion("dict_data_name is null");
            return (Criteria) this;
        }

        public Criteria andDictDataNameIsNotNull() {
            addCriterion("dict_data_name is not null");
            return (Criteria) this;
        }

        public Criteria andDictDataNameEqualTo(String value) {
            addCriterion("dict_data_name =", value, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameNotEqualTo(String value) {
            addCriterion("dict_data_name <>", value, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameGreaterThan(String value) {
            addCriterion("dict_data_name >", value, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameGreaterThanOrEqualTo(String value) {
            addCriterion("dict_data_name >=", value, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameLessThan(String value) {
            addCriterion("dict_data_name <", value, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameLessThanOrEqualTo(String value) {
            addCriterion("dict_data_name <=", value, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameLike(String value) {
            addCriterion("dict_data_name like", value, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameNotLike(String value) {
            addCriterion("dict_data_name not like", value, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameIn(List<String> values) {
            addCriterion("dict_data_name in", values, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameNotIn(List<String> values) {
            addCriterion("dict_data_name not in", values, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameBetween(String value1, String value2) {
            addCriterion("dict_data_name between", value1, value2, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataNameNotBetween(String value1, String value2) {
            addCriterion("dict_data_name not between", value1, value2, "dictDataName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameIsNull() {
            addCriterion("dict_data_short_name is null");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameIsNotNull() {
            addCriterion("dict_data_short_name is not null");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameEqualTo(String value) {
            addCriterion("dict_data_short_name =", value, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameNotEqualTo(String value) {
            addCriterion("dict_data_short_name <>", value, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameGreaterThan(String value) {
            addCriterion("dict_data_short_name >", value, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("dict_data_short_name >=", value, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameLessThan(String value) {
            addCriterion("dict_data_short_name <", value, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameLessThanOrEqualTo(String value) {
            addCriterion("dict_data_short_name <=", value, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameLike(String value) {
            addCriterion("dict_data_short_name like", value, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameNotLike(String value) {
            addCriterion("dict_data_short_name not like", value, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameIn(List<String> values) {
            addCriterion("dict_data_short_name in", values, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameNotIn(List<String> values) {
            addCriterion("dict_data_short_name not in", values, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameBetween(String value1, String value2) {
            addCriterion("dict_data_short_name between", value1, value2, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataShortNameNotBetween(String value1, String value2) {
            addCriterion("dict_data_short_name not between", value1, value2, "dictDataShortName");
            return (Criteria) this;
        }

        public Criteria andDictDataValueIsNull() {
            addCriterion("dict_data_value is null");
            return (Criteria) this;
        }

        public Criteria andDictDataValueIsNotNull() {
            addCriterion("dict_data_value is not null");
            return (Criteria) this;
        }

        public Criteria andDictDataValueEqualTo(String value) {
            addCriterion("dict_data_value =", value, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueNotEqualTo(String value) {
            addCriterion("dict_data_value <>", value, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueGreaterThan(String value) {
            addCriterion("dict_data_value >", value, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueGreaterThanOrEqualTo(String value) {
            addCriterion("dict_data_value >=", value, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueLessThan(String value) {
            addCriterion("dict_data_value <", value, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueLessThanOrEqualTo(String value) {
            addCriterion("dict_data_value <=", value, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueLike(String value) {
            addCriterion("dict_data_value like", value, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueNotLike(String value) {
            addCriterion("dict_data_value not like", value, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueIn(List<String> values) {
            addCriterion("dict_data_value in", values, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueNotIn(List<String> values) {
            addCriterion("dict_data_value not in", values, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueBetween(String value1, String value2) {
            addCriterion("dict_data_value between", value1, value2, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictDataValueNotBetween(String value1, String value2) {
            addCriterion("dict_data_value not between", value1, value2, "dictDataValue");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeIsNull() {
            addCriterion("dict_biz_code is null");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeIsNotNull() {
            addCriterion("dict_biz_code is not null");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeEqualTo(String value) {
            addCriterion("dict_biz_code =", value, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeNotEqualTo(String value) {
            addCriterion("dict_biz_code <>", value, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeGreaterThan(String value) {
            addCriterion("dict_biz_code >", value, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dict_biz_code >=", value, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeLessThan(String value) {
            addCriterion("dict_biz_code <", value, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeLessThanOrEqualTo(String value) {
            addCriterion("dict_biz_code <=", value, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeLike(String value) {
            addCriterion("dict_biz_code like", value, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeNotLike(String value) {
            addCriterion("dict_biz_code not like", value, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeIn(List<String> values) {
            addCriterion("dict_biz_code in", values, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeNotIn(List<String> values) {
            addCriterion("dict_biz_code not in", values, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeBetween(String value1, String value2) {
            addCriterion("dict_biz_code between", value1, value2, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictBizCodeNotBetween(String value1, String value2) {
            addCriterion("dict_biz_code not between", value1, value2, "dictBizCode");
            return (Criteria) this;
        }

        public Criteria andDictDataSortIsNull() {
            addCriterion("dict_data_sort is null");
            return (Criteria) this;
        }

        public Criteria andDictDataSortIsNotNull() {
            addCriterion("dict_data_sort is not null");
            return (Criteria) this;
        }

        public Criteria andDictDataSortEqualTo(Long value) {
            addCriterion("dict_data_sort =", value, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataSortNotEqualTo(Long value) {
            addCriterion("dict_data_sort <>", value, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataSortGreaterThan(Long value) {
            addCriterion("dict_data_sort >", value, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataSortGreaterThanOrEqualTo(Long value) {
            addCriterion("dict_data_sort >=", value, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataSortLessThan(Long value) {
            addCriterion("dict_data_sort <", value, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataSortLessThanOrEqualTo(Long value) {
            addCriterion("dict_data_sort <=", value, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataSortIn(List<Long> values) {
            addCriterion("dict_data_sort in", values, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataSortNotIn(List<Long> values) {
            addCriterion("dict_data_sort not in", values, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataSortBetween(Long value1, Long value2) {
            addCriterion("dict_data_sort between", value1, value2, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataSortNotBetween(Long value1, Long value2) {
            addCriterion("dict_data_sort not between", value1, value2, "dictDataSort");
            return (Criteria) this;
        }

        public Criteria andDictDataDescIsNull() {
            addCriterion("dict_data_desc is null");
            return (Criteria) this;
        }

        public Criteria andDictDataDescIsNotNull() {
            addCriterion("dict_data_desc is not null");
            return (Criteria) this;
        }

        public Criteria andDictDataDescEqualTo(String value) {
            addCriterion("dict_data_desc =", value, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescNotEqualTo(String value) {
            addCriterion("dict_data_desc <>", value, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescGreaterThan(String value) {
            addCriterion("dict_data_desc >", value, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescGreaterThanOrEqualTo(String value) {
            addCriterion("dict_data_desc >=", value, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescLessThan(String value) {
            addCriterion("dict_data_desc <", value, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescLessThanOrEqualTo(String value) {
            addCriterion("dict_data_desc <=", value, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescLike(String value) {
            addCriterion("dict_data_desc like", value, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescNotLike(String value) {
            addCriterion("dict_data_desc not like", value, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescIn(List<String> values) {
            addCriterion("dict_data_desc in", values, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescNotIn(List<String> values) {
            addCriterion("dict_data_desc not in", values, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescBetween(String value1, String value2) {
            addCriterion("dict_data_desc between", value1, value2, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andDictDataDescNotBetween(String value1, String value2) {
            addCriterion("dict_data_desc not between", value1, value2, "dictDataDesc");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by_ =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by_ <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by_ >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by_ >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by_ <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by_ <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by_ like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by_ not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by_ in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by_ not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by_ between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by_ not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time_ =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time_ <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time_ >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time_ >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time_ <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time_ <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time_ in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time_ not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time_ between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time_ not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by_ is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by_ is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by_ =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by_ <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by_ >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by_ >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by_ <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by_ <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by_ like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by_ not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by_ in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by_ not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by_ between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by_ not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time_ is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time_ =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time_ <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time_ >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time_ >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time_ <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time_ <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time_ in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time_ not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time_ between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time_ not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDataStatusIsNull() {
            addCriterion("data_status is null");
            return (Criteria) this;
        }

        public Criteria andDataStatusIsNotNull() {
            addCriterion("data_status is not null");
            return (Criteria) this;
        }

        public Criteria andDataStatusEqualTo(String value) {
            addCriterion("data_status =", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotEqualTo(String value) {
            addCriterion("data_status <>", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusGreaterThan(String value) {
            addCriterion("data_status >", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusGreaterThanOrEqualTo(String value) {
            addCriterion("data_status >=", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLessThan(String value) {
            addCriterion("data_status <", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLessThanOrEqualTo(String value) {
            addCriterion("data_status <=", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLike(String value) {
            addCriterion("data_status like", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotLike(String value) {
            addCriterion("data_status not like", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusIn(List<String> values) {
            addCriterion("data_status in", values, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotIn(List<String> values) {
            addCriterion("data_status not in", values, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusBetween(String value1, String value2) {
            addCriterion("data_status between", value1, value2, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotBetween(String value1, String value2) {
            addCriterion("data_status not between", value1, value2, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataSyncIsNull() {
            addCriterion("data_sync is null");
            return (Criteria) this;
        }

        public Criteria andDataSyncIsNotNull() {
            addCriterion("data_sync is not null");
            return (Criteria) this;
        }

        public Criteria andDataSyncEqualTo(String value) {
            addCriterion("data_sync =", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncNotEqualTo(String value) {
            addCriterion("data_sync <>", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncGreaterThan(String value) {
            addCriterion("data_sync >", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncGreaterThanOrEqualTo(String value) {
            addCriterion("data_sync >=", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncLessThan(String value) {
            addCriterion("data_sync <", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncLessThanOrEqualTo(String value) {
            addCriterion("data_sync <=", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncLike(String value) {
            addCriterion("data_sync like", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncNotLike(String value) {
            addCriterion("data_sync not like", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncIn(List<String> values) {
            addCriterion("data_sync in", values, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncNotIn(List<String> values) {
            addCriterion("data_sync not in", values, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncBetween(String value1, String value2) {
            addCriterion("data_sync between", value1, value2, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncNotBetween(String value1, String value2) {
            addCriterion("data_sync not between", value1, value2, "dataSync");
            return (Criteria) this;
        }

        public Criteria andHospitalNoIsNull() {
            addCriterion("hospital_no is null");
            return (Criteria) this;
        }

        public Criteria andHospitalNoIsNotNull() {
            addCriterion("hospital_no is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalNoEqualTo(String value) {
            addCriterion("hospital_no =", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoNotEqualTo(String value) {
            addCriterion("hospital_no <>", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoGreaterThan(String value) {
            addCriterion("hospital_no >", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_no >=", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoLessThan(String value) {
            addCriterion("hospital_no <", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoLessThanOrEqualTo(String value) {
            addCriterion("hospital_no <=", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoLike(String value) {
            addCriterion("hospital_no like", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoNotLike(String value) {
            addCriterion("hospital_no not like", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoIn(List<String> values) {
            addCriterion("hospital_no in", values, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoNotIn(List<String> values) {
            addCriterion("hospital_no not in", values, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoBetween(String value1, String value2) {
            addCriterion("hospital_no between", value1, value2, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoNotBetween(String value1, String value2) {
            addCriterion("hospital_no not between", value1, value2, "hospitalNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_dict_data
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}