package com.hongster.dis.common.model.dialysis;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DiaSummary implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.summary_id
     *
     * @mbg.generated
     */
    private String summaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.dia_record_id
     *
     * @mbg.generated
     */
    private String diaRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.after_plan_weight
     *
     * @mbg.generated
     */
    private BigDecimal afterPlanWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.after_real_weight
     *
     * @mbg.generated
     */
    private BigDecimal afterRealWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.differ_weight
     *
     * @mbg.generated
     */
    private BigDecimal differWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.actual_dehydration
     *
     * @mbg.generated
     */
    private BigDecimal actualDehydration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.machine_dehydration
     *
     * @mbg.generated
     */
    private BigDecimal machineDehydration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.dialysis_time_hour
     *
     * @mbg.generated
     */
    private Integer dialysisTimeHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.dialysis_time_min
     *
     * @mbg.generated
     */
    private Integer dialysisTimeMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.systolic_pressure
     *
     * @mbg.generated
     */
    private Integer systolicPressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.diastolic_pressure
     *
     * @mbg.generated
     */
    private Integer diastolicPressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.pulse
     *
     * @mbg.generated
     */
    private Integer pulse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.substitute_mode
     *
     * @mbg.generated
     */
    private String substituteMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.replacement_fluid_total
     *
     * @mbg.generated
     */
    private BigDecimal replacementFluidTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.rel_replacement_fluid_total
     *
     * @mbg.generated
     */
    private BigDecimal relReplacementFluidTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.replacement_fluid_flow_rate
     *
     * @mbg.generated
     */
    private Integer replacementFluidFlowRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.fall_assess
     *
     * @mbg.generated
     */
    private String fallAssess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.catheter_drop
     *
     * @mbg.generated
     */
    private String catheterDrop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.dia_coagulation
     *
     * @mbg.generated
     */
    private String diaCoagulation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.dialyzer_change
     *
     * @mbg.generated
     */
    private String dialyzerChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.blood_clotting
     *
     * @mbg.generated
     */
    private String bloodClotting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.piping_change
     *
     * @mbg.generated
     */
    private String pipingChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.fever
     *
     * @mbg.generated
     */
    private String fever;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.dialysate_intake_type
     *
     * @mbg.generated
     */
    private String dialysateIntakeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.dialysate_intake
     *
     * @mbg.generated
     */
    private BigDecimal dialysateIntake;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.gait_watch
     *
     * @mbg.generated
     */
    private String gaitWatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.accompany_user
     *
     * @mbg.generated
     */
    private String accompanyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.hemostasis
     *
     * @mbg.generated
     */
    private String hemostasis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.hemostasis_time
     *
     * @mbg.generated
     */
    private String hemostasisTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.fistula_tremor
     *
     * @mbg.generated
     */
    private String fistulaTremor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.fistula_noise
     *
     * @mbg.generated
     */
    private String fistulaNoise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.fistula_other
     *
     * @mbg.generated
     */
    private String fistulaOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.dressing_change
     *
     * @mbg.generated
     */
    private String dressingChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.measuring_part
     *
     * @mbg.generated
     */
    private String measuringPart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.sealing_method
     *
     * @mbg.generated
     */
    private String sealingMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.capacity_a
     *
     * @mbg.generated
     */
    private BigDecimal capacityA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.capacity_v
     *
     * @mbg.generated
     */
    private BigDecimal capacityV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.drug_sealing
     *
     * @mbg.generated
     */
    private String drugSealing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.catheter_artery_side
     *
     * @mbg.generated
     */
    private String catheterArterySide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.catheter_vein_side
     *
     * @mbg.generated
     */
    private String catheterVeinSide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.washpipe_user
     *
     * @mbg.generated
     */
    private String washpipeUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.puncture_user
     *
     * @mbg.generated
     */
    private String punctureUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.blood_receiver
     *
     * @mbg.generated
     */
    private String bloodReceiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.rebleeding_user
     *
     * @mbg.generated
     */
    private String rebleedingUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.inspector
     *
     * @mbg.generated
     */
    private String inspector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.principal_nurse
     *
     * @mbg.generated
     */
    private String principalNurse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.check_nurse
     *
     * @mbg.generated
     */
    private String checkNurse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.doctor_sign
     *
     * @mbg.generated
     */
    private String doctorSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.save_status
     *
     * @mbg.generated
     */
    private String saveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.create_by_
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.create_time_
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.update_by_
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.update_time_
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.data_status
     *
     * @mbg.generated
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.data_sync
     *
     * @mbg.generated
     */
    private String dataSync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dia_summary.hospital_no
     *
     * @mbg.generated
     */
    private String hospitalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.summary_id
     *
     * @return the value of dia_summary.summary_id
     *
     * @mbg.generated
     */
    public String getSummaryId() {
        return summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.summary_id
     *
     * @param summaryId the value for dia_summary.summary_id
     *
     * @mbg.generated
     */
    public void setSummaryId(String summaryId) {
        this.summaryId = summaryId == null ? null : summaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.dia_record_id
     *
     * @return the value of dia_summary.dia_record_id
     *
     * @mbg.generated
     */
    public String getDiaRecordId() {
        return diaRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.dia_record_id
     *
     * @param diaRecordId the value for dia_summary.dia_record_id
     *
     * @mbg.generated
     */
    public void setDiaRecordId(String diaRecordId) {
        this.diaRecordId = diaRecordId == null ? null : diaRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.after_plan_weight
     *
     * @return the value of dia_summary.after_plan_weight
     *
     * @mbg.generated
     */
    public BigDecimal getAfterPlanWeight() {
        return afterPlanWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.after_plan_weight
     *
     * @param afterPlanWeight the value for dia_summary.after_plan_weight
     *
     * @mbg.generated
     */
    public void setAfterPlanWeight(BigDecimal afterPlanWeight) {
        this.afterPlanWeight = afterPlanWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.after_real_weight
     *
     * @return the value of dia_summary.after_real_weight
     *
     * @mbg.generated
     */
    public BigDecimal getAfterRealWeight() {
        return afterRealWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.after_real_weight
     *
     * @param afterRealWeight the value for dia_summary.after_real_weight
     *
     * @mbg.generated
     */
    public void setAfterRealWeight(BigDecimal afterRealWeight) {
        this.afterRealWeight = afterRealWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.differ_weight
     *
     * @return the value of dia_summary.differ_weight
     *
     * @mbg.generated
     */
    public BigDecimal getDifferWeight() {
        return differWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.differ_weight
     *
     * @param differWeight the value for dia_summary.differ_weight
     *
     * @mbg.generated
     */
    public void setDifferWeight(BigDecimal differWeight) {
        this.differWeight = differWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.actual_dehydration
     *
     * @return the value of dia_summary.actual_dehydration
     *
     * @mbg.generated
     */
    public BigDecimal getActualDehydration() {
        return actualDehydration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.actual_dehydration
     *
     * @param actualDehydration the value for dia_summary.actual_dehydration
     *
     * @mbg.generated
     */
    public void setActualDehydration(BigDecimal actualDehydration) {
        this.actualDehydration = actualDehydration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.machine_dehydration
     *
     * @return the value of dia_summary.machine_dehydration
     *
     * @mbg.generated
     */
    public BigDecimal getMachineDehydration() {
        return machineDehydration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.machine_dehydration
     *
     * @param machineDehydration the value for dia_summary.machine_dehydration
     *
     * @mbg.generated
     */
    public void setMachineDehydration(BigDecimal machineDehydration) {
        this.machineDehydration = machineDehydration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.dialysis_time_hour
     *
     * @return the value of dia_summary.dialysis_time_hour
     *
     * @mbg.generated
     */
    public Integer getDialysisTimeHour() {
        return dialysisTimeHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.dialysis_time_hour
     *
     * @param dialysisTimeHour the value for dia_summary.dialysis_time_hour
     *
     * @mbg.generated
     */
    public void setDialysisTimeHour(Integer dialysisTimeHour) {
        this.dialysisTimeHour = dialysisTimeHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.dialysis_time_min
     *
     * @return the value of dia_summary.dialysis_time_min
     *
     * @mbg.generated
     */
    public Integer getDialysisTimeMin() {
        return dialysisTimeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.dialysis_time_min
     *
     * @param dialysisTimeMin the value for dia_summary.dialysis_time_min
     *
     * @mbg.generated
     */
    public void setDialysisTimeMin(Integer dialysisTimeMin) {
        this.dialysisTimeMin = dialysisTimeMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.systolic_pressure
     *
     * @return the value of dia_summary.systolic_pressure
     *
     * @mbg.generated
     */
    public Integer getSystolicPressure() {
        return systolicPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.systolic_pressure
     *
     * @param systolicPressure the value for dia_summary.systolic_pressure
     *
     * @mbg.generated
     */
    public void setSystolicPressure(Integer systolicPressure) {
        this.systolicPressure = systolicPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.diastolic_pressure
     *
     * @return the value of dia_summary.diastolic_pressure
     *
     * @mbg.generated
     */
    public Integer getDiastolicPressure() {
        return diastolicPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.diastolic_pressure
     *
     * @param diastolicPressure the value for dia_summary.diastolic_pressure
     *
     * @mbg.generated
     */
    public void setDiastolicPressure(Integer diastolicPressure) {
        this.diastolicPressure = diastolicPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.pulse
     *
     * @return the value of dia_summary.pulse
     *
     * @mbg.generated
     */
    public Integer getPulse() {
        return pulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.pulse
     *
     * @param pulse the value for dia_summary.pulse
     *
     * @mbg.generated
     */
    public void setPulse(Integer pulse) {
        this.pulse = pulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.substitute_mode
     *
     * @return the value of dia_summary.substitute_mode
     *
     * @mbg.generated
     */
    public String getSubstituteMode() {
        return substituteMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.substitute_mode
     *
     * @param substituteMode the value for dia_summary.substitute_mode
     *
     * @mbg.generated
     */
    public void setSubstituteMode(String substituteMode) {
        this.substituteMode = substituteMode == null ? null : substituteMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.replacement_fluid_total
     *
     * @return the value of dia_summary.replacement_fluid_total
     *
     * @mbg.generated
     */
    public BigDecimal getReplacementFluidTotal() {
        return replacementFluidTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.replacement_fluid_total
     *
     * @param replacementFluidTotal the value for dia_summary.replacement_fluid_total
     *
     * @mbg.generated
     */
    public void setReplacementFluidTotal(BigDecimal replacementFluidTotal) {
        this.replacementFluidTotal = replacementFluidTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.rel_replacement_fluid_total
     *
     * @return the value of dia_summary.rel_replacement_fluid_total
     *
     * @mbg.generated
     */
    public BigDecimal getRelReplacementFluidTotal() {
        return relReplacementFluidTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.rel_replacement_fluid_total
     *
     * @param relReplacementFluidTotal the value for dia_summary.rel_replacement_fluid_total
     *
     * @mbg.generated
     */
    public void setRelReplacementFluidTotal(BigDecimal relReplacementFluidTotal) {
        this.relReplacementFluidTotal = relReplacementFluidTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.replacement_fluid_flow_rate
     *
     * @return the value of dia_summary.replacement_fluid_flow_rate
     *
     * @mbg.generated
     */
    public Integer getReplacementFluidFlowRate() {
        return replacementFluidFlowRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.replacement_fluid_flow_rate
     *
     * @param replacementFluidFlowRate the value for dia_summary.replacement_fluid_flow_rate
     *
     * @mbg.generated
     */
    public void setReplacementFluidFlowRate(Integer replacementFluidFlowRate) {
        this.replacementFluidFlowRate = replacementFluidFlowRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.fall_assess
     *
     * @return the value of dia_summary.fall_assess
     *
     * @mbg.generated
     */
    public String getFallAssess() {
        return fallAssess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.fall_assess
     *
     * @param fallAssess the value for dia_summary.fall_assess
     *
     * @mbg.generated
     */
    public void setFallAssess(String fallAssess) {
        this.fallAssess = fallAssess == null ? null : fallAssess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.catheter_drop
     *
     * @return the value of dia_summary.catheter_drop
     *
     * @mbg.generated
     */
    public String getCatheterDrop() {
        return catheterDrop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.catheter_drop
     *
     * @param catheterDrop the value for dia_summary.catheter_drop
     *
     * @mbg.generated
     */
    public void setCatheterDrop(String catheterDrop) {
        this.catheterDrop = catheterDrop == null ? null : catheterDrop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.dia_coagulation
     *
     * @return the value of dia_summary.dia_coagulation
     *
     * @mbg.generated
     */
    public String getDiaCoagulation() {
        return diaCoagulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.dia_coagulation
     *
     * @param diaCoagulation the value for dia_summary.dia_coagulation
     *
     * @mbg.generated
     */
    public void setDiaCoagulation(String diaCoagulation) {
        this.diaCoagulation = diaCoagulation == null ? null : diaCoagulation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.dialyzer_change
     *
     * @return the value of dia_summary.dialyzer_change
     *
     * @mbg.generated
     */
    public String getDialyzerChange() {
        return dialyzerChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.dialyzer_change
     *
     * @param dialyzerChange the value for dia_summary.dialyzer_change
     *
     * @mbg.generated
     */
    public void setDialyzerChange(String dialyzerChange) {
        this.dialyzerChange = dialyzerChange == null ? null : dialyzerChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.blood_clotting
     *
     * @return the value of dia_summary.blood_clotting
     *
     * @mbg.generated
     */
    public String getBloodClotting() {
        return bloodClotting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.blood_clotting
     *
     * @param bloodClotting the value for dia_summary.blood_clotting
     *
     * @mbg.generated
     */
    public void setBloodClotting(String bloodClotting) {
        this.bloodClotting = bloodClotting == null ? null : bloodClotting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.piping_change
     *
     * @return the value of dia_summary.piping_change
     *
     * @mbg.generated
     */
    public String getPipingChange() {
        return pipingChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.piping_change
     *
     * @param pipingChange the value for dia_summary.piping_change
     *
     * @mbg.generated
     */
    public void setPipingChange(String pipingChange) {
        this.pipingChange = pipingChange == null ? null : pipingChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.fever
     *
     * @return the value of dia_summary.fever
     *
     * @mbg.generated
     */
    public String getFever() {
        return fever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.fever
     *
     * @param fever the value for dia_summary.fever
     *
     * @mbg.generated
     */
    public void setFever(String fever) {
        this.fever = fever == null ? null : fever.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.dialysate_intake_type
     *
     * @return the value of dia_summary.dialysate_intake_type
     *
     * @mbg.generated
     */
    public String getDialysateIntakeType() {
        return dialysateIntakeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.dialysate_intake_type
     *
     * @param dialysateIntakeType the value for dia_summary.dialysate_intake_type
     *
     * @mbg.generated
     */
    public void setDialysateIntakeType(String dialysateIntakeType) {
        this.dialysateIntakeType = dialysateIntakeType == null ? null : dialysateIntakeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.dialysate_intake
     *
     * @return the value of dia_summary.dialysate_intake
     *
     * @mbg.generated
     */
    public BigDecimal getDialysateIntake() {
        return dialysateIntake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.dialysate_intake
     *
     * @param dialysateIntake the value for dia_summary.dialysate_intake
     *
     * @mbg.generated
     */
    public void setDialysateIntake(BigDecimal dialysateIntake) {
        this.dialysateIntake = dialysateIntake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.gait_watch
     *
     * @return the value of dia_summary.gait_watch
     *
     * @mbg.generated
     */
    public String getGaitWatch() {
        return gaitWatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.gait_watch
     *
     * @param gaitWatch the value for dia_summary.gait_watch
     *
     * @mbg.generated
     */
    public void setGaitWatch(String gaitWatch) {
        this.gaitWatch = gaitWatch == null ? null : gaitWatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.accompany_user
     *
     * @return the value of dia_summary.accompany_user
     *
     * @mbg.generated
     */
    public String getAccompanyUser() {
        return accompanyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.accompany_user
     *
     * @param accompanyUser the value for dia_summary.accompany_user
     *
     * @mbg.generated
     */
    public void setAccompanyUser(String accompanyUser) {
        this.accompanyUser = accompanyUser == null ? null : accompanyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.hemostasis
     *
     * @return the value of dia_summary.hemostasis
     *
     * @mbg.generated
     */
    public String getHemostasis() {
        return hemostasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.hemostasis
     *
     * @param hemostasis the value for dia_summary.hemostasis
     *
     * @mbg.generated
     */
    public void setHemostasis(String hemostasis) {
        this.hemostasis = hemostasis == null ? null : hemostasis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.hemostasis_time
     *
     * @return the value of dia_summary.hemostasis_time
     *
     * @mbg.generated
     */
    public String getHemostasisTime() {
        return hemostasisTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.hemostasis_time
     *
     * @param hemostasisTime the value for dia_summary.hemostasis_time
     *
     * @mbg.generated
     */
    public void setHemostasisTime(String hemostasisTime) {
        this.hemostasisTime = hemostasisTime == null ? null : hemostasisTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.fistula_tremor
     *
     * @return the value of dia_summary.fistula_tremor
     *
     * @mbg.generated
     */
    public String getFistulaTremor() {
        return fistulaTremor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.fistula_tremor
     *
     * @param fistulaTremor the value for dia_summary.fistula_tremor
     *
     * @mbg.generated
     */
    public void setFistulaTremor(String fistulaTremor) {
        this.fistulaTremor = fistulaTremor == null ? null : fistulaTremor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.fistula_noise
     *
     * @return the value of dia_summary.fistula_noise
     *
     * @mbg.generated
     */
    public String getFistulaNoise() {
        return fistulaNoise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.fistula_noise
     *
     * @param fistulaNoise the value for dia_summary.fistula_noise
     *
     * @mbg.generated
     */
    public void setFistulaNoise(String fistulaNoise) {
        this.fistulaNoise = fistulaNoise == null ? null : fistulaNoise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.fistula_other
     *
     * @return the value of dia_summary.fistula_other
     *
     * @mbg.generated
     */
    public String getFistulaOther() {
        return fistulaOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.fistula_other
     *
     * @param fistulaOther the value for dia_summary.fistula_other
     *
     * @mbg.generated
     */
    public void setFistulaOther(String fistulaOther) {
        this.fistulaOther = fistulaOther == null ? null : fistulaOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.dressing_change
     *
     * @return the value of dia_summary.dressing_change
     *
     * @mbg.generated
     */
    public String getDressingChange() {
        return dressingChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.dressing_change
     *
     * @param dressingChange the value for dia_summary.dressing_change
     *
     * @mbg.generated
     */
    public void setDressingChange(String dressingChange) {
        this.dressingChange = dressingChange == null ? null : dressingChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.measuring_part
     *
     * @return the value of dia_summary.measuring_part
     *
     * @mbg.generated
     */
    public String getMeasuringPart() {
        return measuringPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.measuring_part
     *
     * @param measuringPart the value for dia_summary.measuring_part
     *
     * @mbg.generated
     */
    public void setMeasuringPart(String measuringPart) {
        this.measuringPart = measuringPart == null ? null : measuringPart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.sealing_method
     *
     * @return the value of dia_summary.sealing_method
     *
     * @mbg.generated
     */
    public String getSealingMethod() {
        return sealingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.sealing_method
     *
     * @param sealingMethod the value for dia_summary.sealing_method
     *
     * @mbg.generated
     */
    public void setSealingMethod(String sealingMethod) {
        this.sealingMethod = sealingMethod == null ? null : sealingMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.capacity_a
     *
     * @return the value of dia_summary.capacity_a
     *
     * @mbg.generated
     */
    public BigDecimal getCapacityA() {
        return capacityA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.capacity_a
     *
     * @param capacityA the value for dia_summary.capacity_a
     *
     * @mbg.generated
     */
    public void setCapacityA(BigDecimal capacityA) {
        this.capacityA = capacityA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.capacity_v
     *
     * @return the value of dia_summary.capacity_v
     *
     * @mbg.generated
     */
    public BigDecimal getCapacityV() {
        return capacityV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.capacity_v
     *
     * @param capacityV the value for dia_summary.capacity_v
     *
     * @mbg.generated
     */
    public void setCapacityV(BigDecimal capacityV) {
        this.capacityV = capacityV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.drug_sealing
     *
     * @return the value of dia_summary.drug_sealing
     *
     * @mbg.generated
     */
    public String getDrugSealing() {
        return drugSealing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.drug_sealing
     *
     * @param drugSealing the value for dia_summary.drug_sealing
     *
     * @mbg.generated
     */
    public void setDrugSealing(String drugSealing) {
        this.drugSealing = drugSealing == null ? null : drugSealing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.catheter_artery_side
     *
     * @return the value of dia_summary.catheter_artery_side
     *
     * @mbg.generated
     */
    public String getCatheterArterySide() {
        return catheterArterySide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.catheter_artery_side
     *
     * @param catheterArterySide the value for dia_summary.catheter_artery_side
     *
     * @mbg.generated
     */
    public void setCatheterArterySide(String catheterArterySide) {
        this.catheterArterySide = catheterArterySide == null ? null : catheterArterySide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.catheter_vein_side
     *
     * @return the value of dia_summary.catheter_vein_side
     *
     * @mbg.generated
     */
    public String getCatheterVeinSide() {
        return catheterVeinSide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.catheter_vein_side
     *
     * @param catheterVeinSide the value for dia_summary.catheter_vein_side
     *
     * @mbg.generated
     */
    public void setCatheterVeinSide(String catheterVeinSide) {
        this.catheterVeinSide = catheterVeinSide == null ? null : catheterVeinSide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.summary
     *
     * @return the value of dia_summary.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.summary
     *
     * @param summary the value for dia_summary.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.washpipe_user
     *
     * @return the value of dia_summary.washpipe_user
     *
     * @mbg.generated
     */
    public String getWashpipeUser() {
        return washpipeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.washpipe_user
     *
     * @param washpipeUser the value for dia_summary.washpipe_user
     *
     * @mbg.generated
     */
    public void setWashpipeUser(String washpipeUser) {
        this.washpipeUser = washpipeUser == null ? null : washpipeUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.puncture_user
     *
     * @return the value of dia_summary.puncture_user
     *
     * @mbg.generated
     */
    public String getPunctureUser() {
        return punctureUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.puncture_user
     *
     * @param punctureUser the value for dia_summary.puncture_user
     *
     * @mbg.generated
     */
    public void setPunctureUser(String punctureUser) {
        this.punctureUser = punctureUser == null ? null : punctureUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.blood_receiver
     *
     * @return the value of dia_summary.blood_receiver
     *
     * @mbg.generated
     */
    public String getBloodReceiver() {
        return bloodReceiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.blood_receiver
     *
     * @param bloodReceiver the value for dia_summary.blood_receiver
     *
     * @mbg.generated
     */
    public void setBloodReceiver(String bloodReceiver) {
        this.bloodReceiver = bloodReceiver == null ? null : bloodReceiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.rebleeding_user
     *
     * @return the value of dia_summary.rebleeding_user
     *
     * @mbg.generated
     */
    public String getRebleedingUser() {
        return rebleedingUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.rebleeding_user
     *
     * @param rebleedingUser the value for dia_summary.rebleeding_user
     *
     * @mbg.generated
     */
    public void setRebleedingUser(String rebleedingUser) {
        this.rebleedingUser = rebleedingUser == null ? null : rebleedingUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.inspector
     *
     * @return the value of dia_summary.inspector
     *
     * @mbg.generated
     */
    public String getInspector() {
        return inspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.inspector
     *
     * @param inspector the value for dia_summary.inspector
     *
     * @mbg.generated
     */
    public void setInspector(String inspector) {
        this.inspector = inspector == null ? null : inspector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.principal_nurse
     *
     * @return the value of dia_summary.principal_nurse
     *
     * @mbg.generated
     */
    public String getPrincipalNurse() {
        return principalNurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.principal_nurse
     *
     * @param principalNurse the value for dia_summary.principal_nurse
     *
     * @mbg.generated
     */
    public void setPrincipalNurse(String principalNurse) {
        this.principalNurse = principalNurse == null ? null : principalNurse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.check_nurse
     *
     * @return the value of dia_summary.check_nurse
     *
     * @mbg.generated
     */
    public String getCheckNurse() {
        return checkNurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.check_nurse
     *
     * @param checkNurse the value for dia_summary.check_nurse
     *
     * @mbg.generated
     */
    public void setCheckNurse(String checkNurse) {
        this.checkNurse = checkNurse == null ? null : checkNurse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.doctor_sign
     *
     * @return the value of dia_summary.doctor_sign
     *
     * @mbg.generated
     */
    public String getDoctorSign() {
        return doctorSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.doctor_sign
     *
     * @param doctorSign the value for dia_summary.doctor_sign
     *
     * @mbg.generated
     */
    public void setDoctorSign(String doctorSign) {
        this.doctorSign = doctorSign == null ? null : doctorSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.save_status
     *
     * @return the value of dia_summary.save_status
     *
     * @mbg.generated
     */
    public String getSaveStatus() {
        return saveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.save_status
     *
     * @param saveStatus the value for dia_summary.save_status
     *
     * @mbg.generated
     */
    public void setSaveStatus(String saveStatus) {
        this.saveStatus = saveStatus == null ? null : saveStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.create_by_
     *
     * @return the value of dia_summary.create_by_
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.create_by_
     *
     * @param createBy the value for dia_summary.create_by_
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.create_time_
     *
     * @return the value of dia_summary.create_time_
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.create_time_
     *
     * @param createTime the value for dia_summary.create_time_
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.update_by_
     *
     * @return the value of dia_summary.update_by_
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.update_by_
     *
     * @param updateBy the value for dia_summary.update_by_
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.update_time_
     *
     * @return the value of dia_summary.update_time_
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.update_time_
     *
     * @param updateTime the value for dia_summary.update_time_
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.data_status
     *
     * @return the value of dia_summary.data_status
     *
     * @mbg.generated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.data_status
     *
     * @param dataStatus the value for dia_summary.data_status
     *
     * @mbg.generated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.data_sync
     *
     * @return the value of dia_summary.data_sync
     *
     * @mbg.generated
     */
    public String getDataSync() {
        return dataSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.data_sync
     *
     * @param dataSync the value for dia_summary.data_sync
     *
     * @mbg.generated
     */
    public void setDataSync(String dataSync) {
        this.dataSync = dataSync == null ? null : dataSync.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dia_summary.hospital_no
     *
     * @return the value of dia_summary.hospital_no
     *
     * @mbg.generated
     */
    public String getHospitalNo() {
        return hospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dia_summary.hospital_no
     *
     * @param hospitalNo the value for dia_summary.hospital_no
     *
     * @mbg.generated
     */
    public void setHospitalNo(String hospitalNo) {
        this.hospitalNo = hospitalNo == null ? null : hospitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", summaryId=").append(summaryId);
        sb.append(", diaRecordId=").append(diaRecordId);
        sb.append(", afterPlanWeight=").append(afterPlanWeight);
        sb.append(", afterRealWeight=").append(afterRealWeight);
        sb.append(", differWeight=").append(differWeight);
        sb.append(", actualDehydration=").append(actualDehydration);
        sb.append(", machineDehydration=").append(machineDehydration);
        sb.append(", dialysisTimeHour=").append(dialysisTimeHour);
        sb.append(", dialysisTimeMin=").append(dialysisTimeMin);
        sb.append(", systolicPressure=").append(systolicPressure);
        sb.append(", diastolicPressure=").append(diastolicPressure);
        sb.append(", pulse=").append(pulse);
        sb.append(", substituteMode=").append(substituteMode);
        sb.append(", replacementFluidTotal=").append(replacementFluidTotal);
        sb.append(", relReplacementFluidTotal=").append(relReplacementFluidTotal);
        sb.append(", replacementFluidFlowRate=").append(replacementFluidFlowRate);
        sb.append(", fallAssess=").append(fallAssess);
        sb.append(", catheterDrop=").append(catheterDrop);
        sb.append(", diaCoagulation=").append(diaCoagulation);
        sb.append(", dialyzerChange=").append(dialyzerChange);
        sb.append(", bloodClotting=").append(bloodClotting);
        sb.append(", pipingChange=").append(pipingChange);
        sb.append(", fever=").append(fever);
        sb.append(", dialysateIntakeType=").append(dialysateIntakeType);
        sb.append(", dialysateIntake=").append(dialysateIntake);
        sb.append(", gaitWatch=").append(gaitWatch);
        sb.append(", accompanyUser=").append(accompanyUser);
        sb.append(", hemostasis=").append(hemostasis);
        sb.append(", hemostasisTime=").append(hemostasisTime);
        sb.append(", fistulaTremor=").append(fistulaTremor);
        sb.append(", fistulaNoise=").append(fistulaNoise);
        sb.append(", fistulaOther=").append(fistulaOther);
        sb.append(", dressingChange=").append(dressingChange);
        sb.append(", measuringPart=").append(measuringPart);
        sb.append(", sealingMethod=").append(sealingMethod);
        sb.append(", capacityA=").append(capacityA);
        sb.append(", capacityV=").append(capacityV);
        sb.append(", drugSealing=").append(drugSealing);
        sb.append(", catheterArterySide=").append(catheterArterySide);
        sb.append(", catheterVeinSide=").append(catheterVeinSide);
        sb.append(", summary=").append(summary);
        sb.append(", washpipeUser=").append(washpipeUser);
        sb.append(", punctureUser=").append(punctureUser);
        sb.append(", bloodReceiver=").append(bloodReceiver);
        sb.append(", rebleedingUser=").append(rebleedingUser);
        sb.append(", inspector=").append(inspector);
        sb.append(", principalNurse=").append(principalNurse);
        sb.append(", checkNurse=").append(checkNurse);
        sb.append(", doctorSign=").append(doctorSign);
        sb.append(", saveStatus=").append(saveStatus);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", dataStatus=").append(dataStatus);
        sb.append(", dataSync=").append(dataSync);
        sb.append(", hospitalNo=").append(hospitalNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DiaSummary other = (DiaSummary) that;
        return (this.getSummaryId() == null ? other.getSummaryId() == null : this.getSummaryId().equals(other.getSummaryId()))
            && (this.getDiaRecordId() == null ? other.getDiaRecordId() == null : this.getDiaRecordId().equals(other.getDiaRecordId()))
            && (this.getAfterPlanWeight() == null ? other.getAfterPlanWeight() == null : this.getAfterPlanWeight().equals(other.getAfterPlanWeight()))
            && (this.getAfterRealWeight() == null ? other.getAfterRealWeight() == null : this.getAfterRealWeight().equals(other.getAfterRealWeight()))
            && (this.getDifferWeight() == null ? other.getDifferWeight() == null : this.getDifferWeight().equals(other.getDifferWeight()))
            && (this.getActualDehydration() == null ? other.getActualDehydration() == null : this.getActualDehydration().equals(other.getActualDehydration()))
            && (this.getMachineDehydration() == null ? other.getMachineDehydration() == null : this.getMachineDehydration().equals(other.getMachineDehydration()))
            && (this.getDialysisTimeHour() == null ? other.getDialysisTimeHour() == null : this.getDialysisTimeHour().equals(other.getDialysisTimeHour()))
            && (this.getDialysisTimeMin() == null ? other.getDialysisTimeMin() == null : this.getDialysisTimeMin().equals(other.getDialysisTimeMin()))
            && (this.getSystolicPressure() == null ? other.getSystolicPressure() == null : this.getSystolicPressure().equals(other.getSystolicPressure()))
            && (this.getDiastolicPressure() == null ? other.getDiastolicPressure() == null : this.getDiastolicPressure().equals(other.getDiastolicPressure()))
            && (this.getPulse() == null ? other.getPulse() == null : this.getPulse().equals(other.getPulse()))
            && (this.getSubstituteMode() == null ? other.getSubstituteMode() == null : this.getSubstituteMode().equals(other.getSubstituteMode()))
            && (this.getReplacementFluidTotal() == null ? other.getReplacementFluidTotal() == null : this.getReplacementFluidTotal().equals(other.getReplacementFluidTotal()))
            && (this.getRelReplacementFluidTotal() == null ? other.getRelReplacementFluidTotal() == null : this.getRelReplacementFluidTotal().equals(other.getRelReplacementFluidTotal()))
            && (this.getReplacementFluidFlowRate() == null ? other.getReplacementFluidFlowRate() == null : this.getReplacementFluidFlowRate().equals(other.getReplacementFluidFlowRate()))
            && (this.getFallAssess() == null ? other.getFallAssess() == null : this.getFallAssess().equals(other.getFallAssess()))
            && (this.getCatheterDrop() == null ? other.getCatheterDrop() == null : this.getCatheterDrop().equals(other.getCatheterDrop()))
            && (this.getDiaCoagulation() == null ? other.getDiaCoagulation() == null : this.getDiaCoagulation().equals(other.getDiaCoagulation()))
            && (this.getDialyzerChange() == null ? other.getDialyzerChange() == null : this.getDialyzerChange().equals(other.getDialyzerChange()))
            && (this.getBloodClotting() == null ? other.getBloodClotting() == null : this.getBloodClotting().equals(other.getBloodClotting()))
            && (this.getPipingChange() == null ? other.getPipingChange() == null : this.getPipingChange().equals(other.getPipingChange()))
            && (this.getFever() == null ? other.getFever() == null : this.getFever().equals(other.getFever()))
            && (this.getDialysateIntakeType() == null ? other.getDialysateIntakeType() == null : this.getDialysateIntakeType().equals(other.getDialysateIntakeType()))
            && (this.getDialysateIntake() == null ? other.getDialysateIntake() == null : this.getDialysateIntake().equals(other.getDialysateIntake()))
            && (this.getGaitWatch() == null ? other.getGaitWatch() == null : this.getGaitWatch().equals(other.getGaitWatch()))
            && (this.getAccompanyUser() == null ? other.getAccompanyUser() == null : this.getAccompanyUser().equals(other.getAccompanyUser()))
            && (this.getHemostasis() == null ? other.getHemostasis() == null : this.getHemostasis().equals(other.getHemostasis()))
            && (this.getHemostasisTime() == null ? other.getHemostasisTime() == null : this.getHemostasisTime().equals(other.getHemostasisTime()))
            && (this.getFistulaTremor() == null ? other.getFistulaTremor() == null : this.getFistulaTremor().equals(other.getFistulaTremor()))
            && (this.getFistulaNoise() == null ? other.getFistulaNoise() == null : this.getFistulaNoise().equals(other.getFistulaNoise()))
            && (this.getFistulaOther() == null ? other.getFistulaOther() == null : this.getFistulaOther().equals(other.getFistulaOther()))
            && (this.getDressingChange() == null ? other.getDressingChange() == null : this.getDressingChange().equals(other.getDressingChange()))
            && (this.getMeasuringPart() == null ? other.getMeasuringPart() == null : this.getMeasuringPart().equals(other.getMeasuringPart()))
            && (this.getSealingMethod() == null ? other.getSealingMethod() == null : this.getSealingMethod().equals(other.getSealingMethod()))
            && (this.getCapacityA() == null ? other.getCapacityA() == null : this.getCapacityA().equals(other.getCapacityA()))
            && (this.getCapacityV() == null ? other.getCapacityV() == null : this.getCapacityV().equals(other.getCapacityV()))
            && (this.getDrugSealing() == null ? other.getDrugSealing() == null : this.getDrugSealing().equals(other.getDrugSealing()))
            && (this.getCatheterArterySide() == null ? other.getCatheterArterySide() == null : this.getCatheterArterySide().equals(other.getCatheterArterySide()))
            && (this.getCatheterVeinSide() == null ? other.getCatheterVeinSide() == null : this.getCatheterVeinSide().equals(other.getCatheterVeinSide()))
            && (this.getSummary() == null ? other.getSummary() == null : this.getSummary().equals(other.getSummary()))
            && (this.getWashpipeUser() == null ? other.getWashpipeUser() == null : this.getWashpipeUser().equals(other.getWashpipeUser()))
            && (this.getPunctureUser() == null ? other.getPunctureUser() == null : this.getPunctureUser().equals(other.getPunctureUser()))
            && (this.getBloodReceiver() == null ? other.getBloodReceiver() == null : this.getBloodReceiver().equals(other.getBloodReceiver()))
            && (this.getRebleedingUser() == null ? other.getRebleedingUser() == null : this.getRebleedingUser().equals(other.getRebleedingUser()))
            && (this.getInspector() == null ? other.getInspector() == null : this.getInspector().equals(other.getInspector()))
            && (this.getPrincipalNurse() == null ? other.getPrincipalNurse() == null : this.getPrincipalNurse().equals(other.getPrincipalNurse()))
            && (this.getCheckNurse() == null ? other.getCheckNurse() == null : this.getCheckNurse().equals(other.getCheckNurse()))
            && (this.getDoctorSign() == null ? other.getDoctorSign() == null : this.getDoctorSign().equals(other.getDoctorSign()))
            && (this.getSaveStatus() == null ? other.getSaveStatus() == null : this.getSaveStatus().equals(other.getSaveStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDataStatus() == null ? other.getDataStatus() == null : this.getDataStatus().equals(other.getDataStatus()))
            && (this.getDataSync() == null ? other.getDataSync() == null : this.getDataSync().equals(other.getDataSync()))
            && (this.getHospitalNo() == null ? other.getHospitalNo() == null : this.getHospitalNo().equals(other.getHospitalNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dia_summary
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSummaryId() == null) ? 0 : getSummaryId().hashCode());
        result = prime * result + ((getDiaRecordId() == null) ? 0 : getDiaRecordId().hashCode());
        result = prime * result + ((getAfterPlanWeight() == null) ? 0 : getAfterPlanWeight().hashCode());
        result = prime * result + ((getAfterRealWeight() == null) ? 0 : getAfterRealWeight().hashCode());
        result = prime * result + ((getDifferWeight() == null) ? 0 : getDifferWeight().hashCode());
        result = prime * result + ((getActualDehydration() == null) ? 0 : getActualDehydration().hashCode());
        result = prime * result + ((getMachineDehydration() == null) ? 0 : getMachineDehydration().hashCode());
        result = prime * result + ((getDialysisTimeHour() == null) ? 0 : getDialysisTimeHour().hashCode());
        result = prime * result + ((getDialysisTimeMin() == null) ? 0 : getDialysisTimeMin().hashCode());
        result = prime * result + ((getSystolicPressure() == null) ? 0 : getSystolicPressure().hashCode());
        result = prime * result + ((getDiastolicPressure() == null) ? 0 : getDiastolicPressure().hashCode());
        result = prime * result + ((getPulse() == null) ? 0 : getPulse().hashCode());
        result = prime * result + ((getSubstituteMode() == null) ? 0 : getSubstituteMode().hashCode());
        result = prime * result + ((getReplacementFluidTotal() == null) ? 0 : getReplacementFluidTotal().hashCode());
        result = prime * result + ((getRelReplacementFluidTotal() == null) ? 0 : getRelReplacementFluidTotal().hashCode());
        result = prime * result + ((getReplacementFluidFlowRate() == null) ? 0 : getReplacementFluidFlowRate().hashCode());
        result = prime * result + ((getFallAssess() == null) ? 0 : getFallAssess().hashCode());
        result = prime * result + ((getCatheterDrop() == null) ? 0 : getCatheterDrop().hashCode());
        result = prime * result + ((getDiaCoagulation() == null) ? 0 : getDiaCoagulation().hashCode());
        result = prime * result + ((getDialyzerChange() == null) ? 0 : getDialyzerChange().hashCode());
        result = prime * result + ((getBloodClotting() == null) ? 0 : getBloodClotting().hashCode());
        result = prime * result + ((getPipingChange() == null) ? 0 : getPipingChange().hashCode());
        result = prime * result + ((getFever() == null) ? 0 : getFever().hashCode());
        result = prime * result + ((getDialysateIntakeType() == null) ? 0 : getDialysateIntakeType().hashCode());
        result = prime * result + ((getDialysateIntake() == null) ? 0 : getDialysateIntake().hashCode());
        result = prime * result + ((getGaitWatch() == null) ? 0 : getGaitWatch().hashCode());
        result = prime * result + ((getAccompanyUser() == null) ? 0 : getAccompanyUser().hashCode());
        result = prime * result + ((getHemostasis() == null) ? 0 : getHemostasis().hashCode());
        result = prime * result + ((getHemostasisTime() == null) ? 0 : getHemostasisTime().hashCode());
        result = prime * result + ((getFistulaTremor() == null) ? 0 : getFistulaTremor().hashCode());
        result = prime * result + ((getFistulaNoise() == null) ? 0 : getFistulaNoise().hashCode());
        result = prime * result + ((getFistulaOther() == null) ? 0 : getFistulaOther().hashCode());
        result = prime * result + ((getDressingChange() == null) ? 0 : getDressingChange().hashCode());
        result = prime * result + ((getMeasuringPart() == null) ? 0 : getMeasuringPart().hashCode());
        result = prime * result + ((getSealingMethod() == null) ? 0 : getSealingMethod().hashCode());
        result = prime * result + ((getCapacityA() == null) ? 0 : getCapacityA().hashCode());
        result = prime * result + ((getCapacityV() == null) ? 0 : getCapacityV().hashCode());
        result = prime * result + ((getDrugSealing() == null) ? 0 : getDrugSealing().hashCode());
        result = prime * result + ((getCatheterArterySide() == null) ? 0 : getCatheterArterySide().hashCode());
        result = prime * result + ((getCatheterVeinSide() == null) ? 0 : getCatheterVeinSide().hashCode());
        result = prime * result + ((getSummary() == null) ? 0 : getSummary().hashCode());
        result = prime * result + ((getWashpipeUser() == null) ? 0 : getWashpipeUser().hashCode());
        result = prime * result + ((getPunctureUser() == null) ? 0 : getPunctureUser().hashCode());
        result = prime * result + ((getBloodReceiver() == null) ? 0 : getBloodReceiver().hashCode());
        result = prime * result + ((getRebleedingUser() == null) ? 0 : getRebleedingUser().hashCode());
        result = prime * result + ((getInspector() == null) ? 0 : getInspector().hashCode());
        result = prime * result + ((getPrincipalNurse() == null) ? 0 : getPrincipalNurse().hashCode());
        result = prime * result + ((getCheckNurse() == null) ? 0 : getCheckNurse().hashCode());
        result = prime * result + ((getDoctorSign() == null) ? 0 : getDoctorSign().hashCode());
        result = prime * result + ((getSaveStatus() == null) ? 0 : getSaveStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDataStatus() == null) ? 0 : getDataStatus().hashCode());
        result = prime * result + ((getDataSync() == null) ? 0 : getDataSync().hashCode());
        result = prime * result + ((getHospitalNo() == null) ? 0 : getHospitalNo().hashCode());
        return result;
    }
}