package com.origtek.oas.common.model.patient;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PatPatientHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.patient_history_id
     *
     * @mbg.generated
     */
    private String patientHistoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.patient_id
     *
     * @mbg.generated
     */
    private String patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.customer_type
     *
     * @mbg.generated
     */
    private String customerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.dialysis_total_frequency
     *
     * @mbg.generated
     */
    private String dialysisTotalFrequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.dry_weight
     *
     * @mbg.generated
     */
    private BigDecimal dryWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.dry_weight_adjust
     *
     * @mbg.generated
     */
    private BigDecimal dryWeightAdjust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.additional_weight
     *
     * @mbg.generated
     */
    private BigDecimal additionalWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.infection_status
     *
     * @mbg.generated
     */
    private String infectionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.create_by_
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.create_time_
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.update_by_
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.update_time_
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.data_status
     *
     * @mbg.generated
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.data_sync
     *
     * @mbg.generated
     */
    private String dataSync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.hospital_no
     *
     * @mbg.generated
     */
    private String hospitalNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_patient_history.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.patient_history_id
     *
     * @return the value of pat_patient_history.patient_history_id
     *
     * @mbg.generated
     */
    public String getPatientHistoryId() {
        return patientHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.patient_history_id
     *
     * @param patientHistoryId the value for pat_patient_history.patient_history_id
     *
     * @mbg.generated
     */
    public void setPatientHistoryId(String patientHistoryId) {
        this.patientHistoryId = patientHistoryId == null ? null : patientHistoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.patient_id
     *
     * @return the value of pat_patient_history.patient_id
     *
     * @mbg.generated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.patient_id
     *
     * @param patientId the value for pat_patient_history.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.customer_type
     *
     * @return the value of pat_patient_history.customer_type
     *
     * @mbg.generated
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.customer_type
     *
     * @param customerType the value for pat_patient_history.customer_type
     *
     * @mbg.generated
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.dialysis_total_frequency
     *
     * @return the value of pat_patient_history.dialysis_total_frequency
     *
     * @mbg.generated
     */
    public String getDialysisTotalFrequency() {
        return dialysisTotalFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.dialysis_total_frequency
     *
     * @param dialysisTotalFrequency the value for pat_patient_history.dialysis_total_frequency
     *
     * @mbg.generated
     */
    public void setDialysisTotalFrequency(String dialysisTotalFrequency) {
        this.dialysisTotalFrequency = dialysisTotalFrequency == null ? null : dialysisTotalFrequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.dry_weight
     *
     * @return the value of pat_patient_history.dry_weight
     *
     * @mbg.generated
     */
    public BigDecimal getDryWeight() {
        return dryWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.dry_weight
     *
     * @param dryWeight the value for pat_patient_history.dry_weight
     *
     * @mbg.generated
     */
    public void setDryWeight(BigDecimal dryWeight) {
        this.dryWeight = dryWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.dry_weight_adjust
     *
     * @return the value of pat_patient_history.dry_weight_adjust
     *
     * @mbg.generated
     */
    public BigDecimal getDryWeightAdjust() {
        return dryWeightAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.dry_weight_adjust
     *
     * @param dryWeightAdjust the value for pat_patient_history.dry_weight_adjust
     *
     * @mbg.generated
     */
    public void setDryWeightAdjust(BigDecimal dryWeightAdjust) {
        this.dryWeightAdjust = dryWeightAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.additional_weight
     *
     * @return the value of pat_patient_history.additional_weight
     *
     * @mbg.generated
     */
    public BigDecimal getAdditionalWeight() {
        return additionalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.additional_weight
     *
     * @param additionalWeight the value for pat_patient_history.additional_weight
     *
     * @mbg.generated
     */
    public void setAdditionalWeight(BigDecimal additionalWeight) {
        this.additionalWeight = additionalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.infection_status
     *
     * @return the value of pat_patient_history.infection_status
     *
     * @mbg.generated
     */
    public String getInfectionStatus() {
        return infectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.infection_status
     *
     * @param infectionStatus the value for pat_patient_history.infection_status
     *
     * @mbg.generated
     */
    public void setInfectionStatus(String infectionStatus) {
        this.infectionStatus = infectionStatus == null ? null : infectionStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.create_by_
     *
     * @return the value of pat_patient_history.create_by_
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.create_by_
     *
     * @param createBy the value for pat_patient_history.create_by_
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.create_time_
     *
     * @return the value of pat_patient_history.create_time_
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.create_time_
     *
     * @param createTime the value for pat_patient_history.create_time_
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.update_by_
     *
     * @return the value of pat_patient_history.update_by_
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.update_by_
     *
     * @param updateBy the value for pat_patient_history.update_by_
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.update_time_
     *
     * @return the value of pat_patient_history.update_time_
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.update_time_
     *
     * @param updateTime the value for pat_patient_history.update_time_
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.data_status
     *
     * @return the value of pat_patient_history.data_status
     *
     * @mbg.generated
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.data_status
     *
     * @param dataStatus the value for pat_patient_history.data_status
     *
     * @mbg.generated
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.data_sync
     *
     * @return the value of pat_patient_history.data_sync
     *
     * @mbg.generated
     */
    public String getDataSync() {
        return dataSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.data_sync
     *
     * @param dataSync the value for pat_patient_history.data_sync
     *
     * @mbg.generated
     */
    public void setDataSync(String dataSync) {
        this.dataSync = dataSync == null ? null : dataSync.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.hospital_no
     *
     * @return the value of pat_patient_history.hospital_no
     *
     * @mbg.generated
     */
    public String getHospitalNo() {
        return hospitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.hospital_no
     *
     * @param hospitalNo the value for pat_patient_history.hospital_no
     *
     * @mbg.generated
     */
    public void setHospitalNo(String hospitalNo) {
        this.hospitalNo = hospitalNo == null ? null : hospitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_patient_history.remarks
     *
     * @return the value of pat_patient_history.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_patient_history.remarks
     *
     * @param remarks the value for pat_patient_history.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", patientHistoryId=").append(patientHistoryId);
        sb.append(", patientId=").append(patientId);
        sb.append(", customerType=").append(customerType);
        sb.append(", dialysisTotalFrequency=").append(dialysisTotalFrequency);
        sb.append(", dryWeight=").append(dryWeight);
        sb.append(", dryWeightAdjust=").append(dryWeightAdjust);
        sb.append(", additionalWeight=").append(additionalWeight);
        sb.append(", infectionStatus=").append(infectionStatus);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", dataStatus=").append(dataStatus);
        sb.append(", dataSync=").append(dataSync);
        sb.append(", hospitalNo=").append(hospitalNo);
        sb.append(", remarks=").append(remarks);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PatPatientHistory other = (PatPatientHistory) that;
        return (this.getPatientHistoryId() == null ? other.getPatientHistoryId() == null : this.getPatientHistoryId().equals(other.getPatientHistoryId()))
            && (this.getPatientId() == null ? other.getPatientId() == null : this.getPatientId().equals(other.getPatientId()))
            && (this.getCustomerType() == null ? other.getCustomerType() == null : this.getCustomerType().equals(other.getCustomerType()))
            && (this.getDialysisTotalFrequency() == null ? other.getDialysisTotalFrequency() == null : this.getDialysisTotalFrequency().equals(other.getDialysisTotalFrequency()))
            && (this.getDryWeight() == null ? other.getDryWeight() == null : this.getDryWeight().equals(other.getDryWeight()))
            && (this.getDryWeightAdjust() == null ? other.getDryWeightAdjust() == null : this.getDryWeightAdjust().equals(other.getDryWeightAdjust()))
            && (this.getAdditionalWeight() == null ? other.getAdditionalWeight() == null : this.getAdditionalWeight().equals(other.getAdditionalWeight()))
            && (this.getInfectionStatus() == null ? other.getInfectionStatus() == null : this.getInfectionStatus().equals(other.getInfectionStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDataStatus() == null ? other.getDataStatus() == null : this.getDataStatus().equals(other.getDataStatus()))
            && (this.getDataSync() == null ? other.getDataSync() == null : this.getDataSync().equals(other.getDataSync()))
            && (this.getHospitalNo() == null ? other.getHospitalNo() == null : this.getHospitalNo().equals(other.getHospitalNo()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPatientHistoryId() == null) ? 0 : getPatientHistoryId().hashCode());
        result = prime * result + ((getPatientId() == null) ? 0 : getPatientId().hashCode());
        result = prime * result + ((getCustomerType() == null) ? 0 : getCustomerType().hashCode());
        result = prime * result + ((getDialysisTotalFrequency() == null) ? 0 : getDialysisTotalFrequency().hashCode());
        result = prime * result + ((getDryWeight() == null) ? 0 : getDryWeight().hashCode());
        result = prime * result + ((getDryWeightAdjust() == null) ? 0 : getDryWeightAdjust().hashCode());
        result = prime * result + ((getAdditionalWeight() == null) ? 0 : getAdditionalWeight().hashCode());
        result = prime * result + ((getInfectionStatus() == null) ? 0 : getInfectionStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDataStatus() == null) ? 0 : getDataStatus().hashCode());
        result = prime * result + ((getDataSync() == null) ? 0 : getDataSync().hashCode());
        result = prime * result + ((getHospitalNo() == null) ? 0 : getHospitalNo().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        return result;
    }
}