package com.origtek.oas.common.model.patient;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PatPatientHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public PatPatientHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPatientHistoryIdIsNull() {
            addCriterion("patient_history_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdIsNotNull() {
            addCriterion("patient_history_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdEqualTo(String value) {
            addCriterion("patient_history_id =", value, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdNotEqualTo(String value) {
            addCriterion("patient_history_id <>", value, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdGreaterThan(String value) {
            addCriterion("patient_history_id >", value, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("patient_history_id >=", value, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdLessThan(String value) {
            addCriterion("patient_history_id <", value, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdLessThanOrEqualTo(String value) {
            addCriterion("patient_history_id <=", value, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdLike(String value) {
            addCriterion("patient_history_id like", value, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdNotLike(String value) {
            addCriterion("patient_history_id not like", value, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdIn(List<String> values) {
            addCriterion("patient_history_id in", values, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdNotIn(List<String> values) {
            addCriterion("patient_history_id not in", values, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdBetween(String value1, String value2) {
            addCriterion("patient_history_id between", value1, value2, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientHistoryIdNotBetween(String value1, String value2) {
            addCriterion("patient_history_id not between", value1, value2, "patientHistoryId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("patient_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("patient_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(String value) {
            addCriterion("patient_id =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(String value) {
            addCriterion("patient_id <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(String value) {
            addCriterion("patient_id >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(String value) {
            addCriterion("patient_id >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(String value) {
            addCriterion("patient_id <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(String value) {
            addCriterion("patient_id <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLike(String value) {
            addCriterion("patient_id like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotLike(String value) {
            addCriterion("patient_id not like", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<String> values) {
            addCriterion("patient_id in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<String> values) {
            addCriterion("patient_id not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(String value1, String value2) {
            addCriterion("patient_id between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(String value1, String value2) {
            addCriterion("patient_id not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeIsNull() {
            addCriterion("customer_type is null");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeIsNotNull() {
            addCriterion("customer_type is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeEqualTo(String value) {
            addCriterion("customer_type =", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotEqualTo(String value) {
            addCriterion("customer_type <>", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeGreaterThan(String value) {
            addCriterion("customer_type >", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("customer_type >=", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeLessThan(String value) {
            addCriterion("customer_type <", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeLessThanOrEqualTo(String value) {
            addCriterion("customer_type <=", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeLike(String value) {
            addCriterion("customer_type like", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotLike(String value) {
            addCriterion("customer_type not like", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeIn(List<String> values) {
            addCriterion("customer_type in", values, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotIn(List<String> values) {
            addCriterion("customer_type not in", values, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeBetween(String value1, String value2) {
            addCriterion("customer_type between", value1, value2, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotBetween(String value1, String value2) {
            addCriterion("customer_type not between", value1, value2, "customerType");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyIsNull() {
            addCriterion("dialysis_total_frequency is null");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyIsNotNull() {
            addCriterion("dialysis_total_frequency is not null");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyEqualTo(String value) {
            addCriterion("dialysis_total_frequency =", value, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyNotEqualTo(String value) {
            addCriterion("dialysis_total_frequency <>", value, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyGreaterThan(String value) {
            addCriterion("dialysis_total_frequency >", value, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyGreaterThanOrEqualTo(String value) {
            addCriterion("dialysis_total_frequency >=", value, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyLessThan(String value) {
            addCriterion("dialysis_total_frequency <", value, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyLessThanOrEqualTo(String value) {
            addCriterion("dialysis_total_frequency <=", value, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyLike(String value) {
            addCriterion("dialysis_total_frequency like", value, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyNotLike(String value) {
            addCriterion("dialysis_total_frequency not like", value, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyIn(List<String> values) {
            addCriterion("dialysis_total_frequency in", values, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyNotIn(List<String> values) {
            addCriterion("dialysis_total_frequency not in", values, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyBetween(String value1, String value2) {
            addCriterion("dialysis_total_frequency between", value1, value2, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDialysisTotalFrequencyNotBetween(String value1, String value2) {
            addCriterion("dialysis_total_frequency not between", value1, value2, "dialysisTotalFrequency");
            return (Criteria) this;
        }

        public Criteria andDryWeightIsNull() {
            addCriterion("dry_weight is null");
            return (Criteria) this;
        }

        public Criteria andDryWeightIsNotNull() {
            addCriterion("dry_weight is not null");
            return (Criteria) this;
        }

        public Criteria andDryWeightEqualTo(BigDecimal value) {
            addCriterion("dry_weight =", value, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightNotEqualTo(BigDecimal value) {
            addCriterion("dry_weight <>", value, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightGreaterThan(BigDecimal value) {
            addCriterion("dry_weight >", value, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dry_weight >=", value, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightLessThan(BigDecimal value) {
            addCriterion("dry_weight <", value, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dry_weight <=", value, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightIn(List<BigDecimal> values) {
            addCriterion("dry_weight in", values, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightNotIn(List<BigDecimal> values) {
            addCriterion("dry_weight not in", values, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dry_weight between", value1, value2, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dry_weight not between", value1, value2, "dryWeight");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustIsNull() {
            addCriterion("dry_weight_adjust is null");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustIsNotNull() {
            addCriterion("dry_weight_adjust is not null");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustEqualTo(BigDecimal value) {
            addCriterion("dry_weight_adjust =", value, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustNotEqualTo(BigDecimal value) {
            addCriterion("dry_weight_adjust <>", value, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustGreaterThan(BigDecimal value) {
            addCriterion("dry_weight_adjust >", value, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dry_weight_adjust >=", value, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustLessThan(BigDecimal value) {
            addCriterion("dry_weight_adjust <", value, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dry_weight_adjust <=", value, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustIn(List<BigDecimal> values) {
            addCriterion("dry_weight_adjust in", values, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustNotIn(List<BigDecimal> values) {
            addCriterion("dry_weight_adjust not in", values, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dry_weight_adjust between", value1, value2, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andDryWeightAdjustNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dry_weight_adjust not between", value1, value2, "dryWeightAdjust");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightIsNull() {
            addCriterion("additional_weight is null");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightIsNotNull() {
            addCriterion("additional_weight is not null");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightEqualTo(BigDecimal value) {
            addCriterion("additional_weight =", value, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightNotEqualTo(BigDecimal value) {
            addCriterion("additional_weight <>", value, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightGreaterThan(BigDecimal value) {
            addCriterion("additional_weight >", value, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("additional_weight >=", value, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightLessThan(BigDecimal value) {
            addCriterion("additional_weight <", value, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("additional_weight <=", value, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightIn(List<BigDecimal> values) {
            addCriterion("additional_weight in", values, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightNotIn(List<BigDecimal> values) {
            addCriterion("additional_weight not in", values, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("additional_weight between", value1, value2, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andAdditionalWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("additional_weight not between", value1, value2, "additionalWeight");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusIsNull() {
            addCriterion("infection_status is null");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusIsNotNull() {
            addCriterion("infection_status is not null");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusEqualTo(String value) {
            addCriterion("infection_status =", value, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusNotEqualTo(String value) {
            addCriterion("infection_status <>", value, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusGreaterThan(String value) {
            addCriterion("infection_status >", value, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusGreaterThanOrEqualTo(String value) {
            addCriterion("infection_status >=", value, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusLessThan(String value) {
            addCriterion("infection_status <", value, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusLessThanOrEqualTo(String value) {
            addCriterion("infection_status <=", value, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusLike(String value) {
            addCriterion("infection_status like", value, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusNotLike(String value) {
            addCriterion("infection_status not like", value, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusIn(List<String> values) {
            addCriterion("infection_status in", values, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusNotIn(List<String> values) {
            addCriterion("infection_status not in", values, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusBetween(String value1, String value2) {
            addCriterion("infection_status between", value1, value2, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andInfectionStatusNotBetween(String value1, String value2) {
            addCriterion("infection_status not between", value1, value2, "infectionStatus");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by_ =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by_ <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by_ >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by_ >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by_ <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by_ <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by_ like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by_ not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by_ in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by_ not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by_ between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by_ not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time_ =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time_ <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time_ >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time_ >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time_ <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time_ <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time_ in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time_ not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time_ between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time_ not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by_ is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by_ is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by_ =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by_ <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by_ >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by_ >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by_ <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by_ <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by_ like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by_ not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by_ in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by_ not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by_ between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by_ not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time_ is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time_ =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time_ <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time_ >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time_ >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time_ <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time_ <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time_ in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time_ not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time_ between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time_ not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDataStatusIsNull() {
            addCriterion("data_status is null");
            return (Criteria) this;
        }

        public Criteria andDataStatusIsNotNull() {
            addCriterion("data_status is not null");
            return (Criteria) this;
        }

        public Criteria andDataStatusEqualTo(String value) {
            addCriterion("data_status =", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotEqualTo(String value) {
            addCriterion("data_status <>", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusGreaterThan(String value) {
            addCriterion("data_status >", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusGreaterThanOrEqualTo(String value) {
            addCriterion("data_status >=", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLessThan(String value) {
            addCriterion("data_status <", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLessThanOrEqualTo(String value) {
            addCriterion("data_status <=", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusLike(String value) {
            addCriterion("data_status like", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotLike(String value) {
            addCriterion("data_status not like", value, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusIn(List<String> values) {
            addCriterion("data_status in", values, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotIn(List<String> values) {
            addCriterion("data_status not in", values, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusBetween(String value1, String value2) {
            addCriterion("data_status between", value1, value2, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataStatusNotBetween(String value1, String value2) {
            addCriterion("data_status not between", value1, value2, "dataStatus");
            return (Criteria) this;
        }

        public Criteria andDataSyncIsNull() {
            addCriterion("data_sync is null");
            return (Criteria) this;
        }

        public Criteria andDataSyncIsNotNull() {
            addCriterion("data_sync is not null");
            return (Criteria) this;
        }

        public Criteria andDataSyncEqualTo(String value) {
            addCriterion("data_sync =", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncNotEqualTo(String value) {
            addCriterion("data_sync <>", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncGreaterThan(String value) {
            addCriterion("data_sync >", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncGreaterThanOrEqualTo(String value) {
            addCriterion("data_sync >=", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncLessThan(String value) {
            addCriterion("data_sync <", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncLessThanOrEqualTo(String value) {
            addCriterion("data_sync <=", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncLike(String value) {
            addCriterion("data_sync like", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncNotLike(String value) {
            addCriterion("data_sync not like", value, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncIn(List<String> values) {
            addCriterion("data_sync in", values, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncNotIn(List<String> values) {
            addCriterion("data_sync not in", values, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncBetween(String value1, String value2) {
            addCriterion("data_sync between", value1, value2, "dataSync");
            return (Criteria) this;
        }

        public Criteria andDataSyncNotBetween(String value1, String value2) {
            addCriterion("data_sync not between", value1, value2, "dataSync");
            return (Criteria) this;
        }

        public Criteria andHospitalNoIsNull() {
            addCriterion("hospital_no is null");
            return (Criteria) this;
        }

        public Criteria andHospitalNoIsNotNull() {
            addCriterion("hospital_no is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalNoEqualTo(String value) {
            addCriterion("hospital_no =", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoNotEqualTo(String value) {
            addCriterion("hospital_no <>", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoGreaterThan(String value) {
            addCriterion("hospital_no >", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_no >=", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoLessThan(String value) {
            addCriterion("hospital_no <", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoLessThanOrEqualTo(String value) {
            addCriterion("hospital_no <=", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoLike(String value) {
            addCriterion("hospital_no like", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoNotLike(String value) {
            addCriterion("hospital_no not like", value, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoIn(List<String> values) {
            addCriterion("hospital_no in", values, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoNotIn(List<String> values) {
            addCriterion("hospital_no not in", values, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoBetween(String value1, String value2) {
            addCriterion("hospital_no between", value1, value2, "hospitalNo");
            return (Criteria) this;
        }

        public Criteria andHospitalNoNotBetween(String value1, String value2) {
            addCriterion("hospital_no not between", value1, value2, "hospitalNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pat_patient_history
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pat_patient_history
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}